name: sembast_riverpod
description: Using Sembast with Riverpod
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sembast: ^3.1.1+1
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.3
  freezed: ^1.1.1
  build_runner: ^2.1.7

flutter:
  uses-material-design: true